import Phaser from 'phaser'; import { Player } from '../entities/Player'; import type { Upgrade } from '../systems/LevelSystem';
import { formatTime } from '../systems/progression';
export class GameUI {
 private hp!:Phaser.GameObjects.Text; private level!:Phaser.GameObjects.Text; private timer!:Phaser.GameObjects.Text; private xpFill!:Phaser.GameObjects.Rectangle; private overlay?:Phaser.GameObjects.Container;
 constructor(private scene:Phaser.Scene,private player:Player){this.create();}
 private create(){const w=this.scene.scale.width; this.scene.add.rectangle(w/2,35,Math.min(w-32,780),54,0x090d17,.88).setScrollFactor(0).setDepth(20).setStrokeStyle(1,0xc89b3c); this.hp=this.scene.add.text(w/2-360,26,'',{fontSize:'15px',color:'#f4d58a'}).setScrollFactor(0).setDepth(21); this.level=this.scene.add.text(w/2-185,26,'',{fontSize:'15px',color:'#fff'}).setScrollFactor(0).setDepth(21); this.timer=this.scene.add.text(w/2+285,26,'',{fontFamily:'Marcellus',fontSize:'17px',color:'#f4d58a'}).setScrollFactor(0).setDepth(21); this.scene.add.rectangle(w/2,78,Math.min(w-50,650),8,0x1d2638).setScrollFactor(0).setDepth(20); this.xpFill=this.scene.add.rectangle(w/2-Math.min(w-50,650)/2,78,1,8,0x39d0e7).setOrigin(0,.5).setScrollFactor(0).setDepth(21);}
 update(seconds:number){this.hp.setText(`生命  ${Math.ceil(this.player.hp)} / ${this.player.maxHp}`);this.level.setText(`等级 ${this.player.level}`);this.timer.setText(formatTime(seconds));this.xpFill.width=Math.max(1,Math.min(this.scene.scale.width-50,650)*this.player.xp/this.player.xpNeeded);}
 showUpgrades(items:Upgrade[],pick:(u:Upgrade)=>void){const cx=this.scene.scale.width/2,cy=this.scene.scale.height/2; const parts:Phaser.GameObjects.GameObject[]=[this.scene.add.rectangle(cx,cy,this.scene.scale.width,this.scene.scale.height,0x03050a,.86),this.scene.add.text(cx,cy-155,'选择你的道路',{fontFamily:'Marcellus',fontSize:'34px',color:'#f4d58a'}).setOrigin(.5),this.scene.add.text(cx,cy-112,'升级！命运赐予你三种力量',{fontSize:'14px',color:'#aab3c5'}).setOrigin(.5)];items.forEach((u,i)=>{const x=cx+(i-1)*240;const card=this.scene.add.rectangle(x,cy+15,210,210,0x111827).setStrokeStyle(2,0xc89b3c).setInteractive({useHandCursor:true});card.on('pointerover',()=>card.setFillStyle(0x1d2a40)).on('pointerout',()=>card.setFillStyle(0x111827)).on('pointerdown',()=>pick(u));parts.push(card,this.scene.add.text(x,cy-20,u.title,{fontSize:'21px',fontStyle:'bold',color:'#f4d58a'}).setOrigin(.5),this.scene.add.text(x,cy+28,u.description,{fontSize:'15px',color:'#dbe7f5'}).setOrigin(.5));});this.overlay=this.scene.add.container(0,0,parts).setScrollFactor(0).setDepth(50);}
 hideUpgrades(){this.overlay?.destroy(true);this.overlay=undefined;}
 gameOver(restart:()=>void){const cx=this.scene.scale.width/2,cy=this.scene.scale.height/2;const bg=this.scene.add.rectangle(cx,cy,this.scene.scale.width,this.scene.scale.height,0x05060a,.88).setInteractive();const title=this.scene.add.text(cx,cy-50,'战斗终结',{fontFamily:'Marcellus',fontSize:'48px',color:'#d94a3d'}).setOrigin(.5);const btn=this.scene.add.text(cx,cy+35,'再次踏入战场',{fontSize:'18px',backgroundColor:'#9a6b21',padding:{x:28,y:14}}).setOrigin(.5).setInteractive({useHandCursor:true}).on('pointerdown',restart);this.scene.add.container(0,0,[bg,title,btn]).setScrollFactor(0).setDepth(60);}
}
