import Phaser from 'phaser'; import { Player } from '../entities/Player'; import type { Upgrade } from '../systems/LevelSystem'; import { CLASSES,getClassDefinition,type ClassId } from '../classes';
import { formatTime } from '../systems/progression';
export function showClassSelection(scene:Phaser.Scene,pick:(id:ClassId)=>void){const cx=scene.scale.width/2,cy=scene.scale.height/2,gap=Math.min(245,(scene.scale.width-24)/4),cardW=gap-14;const container=scene.add.container(0,0).setScrollFactor(0).setDepth(200);container.add([scene.add.rectangle(cx,cy,scene.scale.width,scene.scale.height,0x05070d,.98).setInteractive(),scene.add.text(cx,cy-205,'选择你的职业',{fontFamily:'Marcellus',fontSize:'42px',color:'#f4d58a'}).setOrigin(.5),scene.add.text(cx,cy-155,'职业决定初始技能、成长词条与整局玩法',{fontSize:'15px',color:'#aab3c5'}).setOrigin(.5)]);CLASSES.forEach((definition,i)=>{const x=cx+(i-1.5)*gap,card=scene.add.rectangle(x,cy+25,cardW,270,0x111827).setStrokeStyle(3,definition.color).setInteractive({useHandCursor:true});card.on('pointerover',()=>card.setScale(1.03).setFillStyle(0x213047)).on('pointerout',()=>card.setScale(1).setFillStyle(0x111827)).once('pointerdown',()=>{card.disableInteractive();container.destroy(true);pick(definition.id);});container.add([card,scene.add.circle(x,cy-50,31,definition.color,.22).setStrokeStyle(2,definition.color),scene.add.text(x,cy-45,definition.skill.slice(0,1),{fontSize:'28px',color:'#ffffff'}).setOrigin(.5),scene.add.text(x,cy+5,definition.name,{fontSize:'21px',fontStyle:'bold',color:'#f4d58a'}).setOrigin(.5),scene.add.text(x,cy+42,`初始技能 · ${definition.skill}`,{fontSize:'13px',color:'#ffffff'}).setOrigin(.5),scene.add.text(x,cy+88,definition.fantasy,{fontSize:'13px',color:'#aab3c5',wordWrap:{width:cardW-28},align:'center'}).setOrigin(.5)]);});}
export class GameUI {
 private hp!:Phaser.GameObjects.Text; private level!:Phaser.GameObjects.Text; private timer!:Phaser.GameObjects.Text; private rage!:Phaser.GameObjects.Text; private xpFill!:Phaser.GameObjects.Rectangle; private overlay?:Phaser.GameObjects.Container;
 constructor(private scene:Phaser.Scene,private player:Player){this.create();}
 private create(){const w=this.scene.scale.width; this.scene.add.rectangle(w/2,35,Math.min(w-32,860),54,0x090d17,.88).setScrollFactor(0).setDepth(20).setStrokeStyle(1,0xc89b3c); this.hp=this.scene.add.text(w/2-390,26,'',{fontSize:'15px',color:'#f4d58a'}).setScrollFactor(0).setDepth(21); this.level=this.scene.add.text(w/2-205,26,'',{fontSize:'15px',color:'#fff'}).setScrollFactor(0).setDepth(21); this.rage=this.scene.add.text(w/2-65,26,'',{fontSize:'15px',color:'#ff884d'}).setScrollFactor(0).setDepth(21); this.timer=this.scene.add.text(w/2+325,26,'',{fontFamily:'Marcellus',fontSize:'17px',color:'#f4d58a'}).setScrollFactor(0).setDepth(21); this.scene.add.text(w/2,108,'狂战士 · 狂暴  |  旋风斩自动释放',{fontSize:'13px',color:'#d6a85d'}).setOrigin(.5).setScrollFactor(0).setDepth(21); this.scene.add.rectangle(w/2,78,Math.min(w-50,650),8,0x1d2638).setScrollFactor(0).setDepth(20); this.xpFill=this.scene.add.rectangle(w/2-Math.min(w-50,650)/2,78,1,8,0x39d0e7).setOrigin(0,.5).setScrollFactor(0).setDepth(21);}
 update(seconds:number){this.hp.setText(`生命 ${Math.ceil(this.player.hp)} / ${this.player.maxHp}`);this.level.setText(`等级 ${this.player.level}`);this.rage.setText(`怒气 ${Math.floor(this.player.rage)} / ${this.player.maxRage}`);this.timer.setText(formatTime(seconds));this.xpFill.width=Math.max(1,Math.min(this.scene.scale.width-50,650)*this.player.xp/this.player.xpNeeded);}
 showUpgrades(items:Upgrade[],pick:(u:Upgrade)=>void){const cx=this.scene.scale.width/2,cy=this.scene.scale.height/2,gap=Math.min(235,(this.scene.scale.width-30)/4),cardW=gap-16; const parts:Phaser.GameObjects.GameObject[]=[this.scene.add.rectangle(cx,cy,this.scene.scale.width,this.scene.scale.height,0x03050a,.9),this.scene.add.text(cx,cy-170,'选择狂暴之路',{fontFamily:'Marcellus',fontSize:'34px',color:'#f4d58a'}).setOrigin(.5),this.scene.add.text(cx,cy-126,'升级四选一 · 天赋会改变旋风斩形态',{fontSize:'14px',color:'#aab3c5'}).setOrigin(.5)];items.forEach((u,i)=>{const x=cx+(i-1.5)*gap;const card=this.scene.add.rectangle(x,cy+15,cardW,220,0x111827).setStrokeStyle(2,u.tag==='顶点天赋'?0xff6b35:0xc89b3c).setInteractive({useHandCursor:true});card.on('pointerover',()=>card.setFillStyle(0x1d2a40)).on('pointerout',()=>card.setFillStyle(0x111827)).on('pointerdown',()=>pick(u));parts.push(card,this.scene.add.text(x,cy-58,u.tag,{fontSize:'12px',color:'#e8863b'}).setOrigin(.5),this.scene.add.text(x,cy-16,u.title,{fontSize:'20px',fontStyle:'bold',color:'#f4d58a'}).setOrigin(.5),this.scene.add.text(x,cy+34,u.description,{fontSize:'14px',color:'#dbe7f5',wordWrap:{width:cardW-22},align:'center'}).setOrigin(.5));});this.overlay=this.scene.add.container(0,0,parts).setScrollFactor(0).setDepth(50);}
 hideUpgrades(){this.overlay?.destroy(true);this.overlay=undefined;}
 gameOver(restart:()=>void){const cx=this.scene.scale.width/2,cy=this.scene.scale.height/2;const bg=this.scene.add.rectangle(cx,cy,this.scene.scale.width,this.scene.scale.height,0x05060a,.88).setInteractive();const title=this.scene.add.text(cx,cy-50,'战斗终结',{fontFamily:'Marcellus',fontSize:'48px',color:'#d94a3d'}).setOrigin(.5);const btn=this.scene.add.text(cx,cy+35,'再次踏入战场',{fontSize:'18px',backgroundColor:'#9a6b21',padding:{x:28,y:14}}).setOrigin(.5).setInteractive({useHandCursor:true}).on('pointerdown',restart);this.scene.add.container(0,0,[bg,title,btn]).setScrollFactor(0).setDepth(60);}
}
