import Phaser from 'phaser'; import { Player } from '../entities/Player'; import { Weapon,type SkillTalent } from '../combat/Weapon'; import { GameUI } from '../ui/UI'; import type { ClassId } from '../classes';
export type Upgrade={id:string;title:string;tag:string;description:string;apply:()=>void};
type Talent=Omit<Upgrade,'apply'>&{talent?:SkillTalent;requires?:string;repeat?:boolean};
export class LevelSystem{
 private owned=new Set<string>();private choosing=false;private queued=0;
 constructor(private scene:Phaser.Scene,private player:Player,private weapon:Weapon,private ui:GameUI,private classId:ClassId){}
 show(){if(this.choosing){this.queued++;return;}this.choosing=true;this.scene.physics.pause();const available=this.pool().filter(t=>(!t.requires||this.owned.has(t.requires))&&(t.repeat||!this.owned.has(t.id)));const items=Phaser.Utils.Array.Shuffle(available).slice(0,4).map(t=>({...t,apply:()=>this.apply(t)}));this.ui.showUpgrades(items,u=>{if(!this.choosing)return;this.choosing=false;u.apply();this.ui.hideUpgrades();this.scene.physics.resume();if(this.queued){this.queued--;this.scene.time.delayedCall(0,()=>this.show());}});}
 private apply(t:Talent){if(!t.repeat)this.owned.add(t.id);if(t.talent)this.weapon.applyTalent(t.talent);if(t.id==='power')this.player.attack*=1.18;if(t.id==='stride')this.player.speed*=1.12;if(t.id==='vitality'){this.player.maxHp+=20;this.player.heal(20);}}
 private pool():Talent[]{const common:Talent[]=[{id:'power',title:'残酷武器',tag:'通用强化',description:'技能伤害 +18%',repeat:true},{id:'stride',title:'迅捷步法',tag:'通用强化',description:'移动速度 +12%',repeat:true},{id:'vitality',title:'坚韧体魄',tag:'生存强化',description:'最大生命 +20，并立即回复',repeat:true}];
  if(this.classId==='berserker')return[...common,{id:'range',title:'扩张利刃',tag:'旋风斩',description:'范围 +20%',talent:'range',repeat:true},{id:'duration',title:'延长风暴',tag:'旋风斩',description:'持续时间 +1 秒',talent:'duration',repeat:true},{id:'fury',title:'沸腾怒火',tag:'狂怒',description:'命中产生双倍怒气',talent:'fury'},{id:'twin',title:'双斧',tag:'狂怒',description:'追加 55% 反向斩击',talent:'twin'},{id:'cooldown',title:'越战越勇',tag:'狂怒',description:'每命中10敌人延长旋转',talent:'cooldown',requires:'fury'},{id:'blood',title:'血路',tag:'狂怒',description:'击杀恢复 1% 生命',talent:'blood'},{id:'eternal',title:'永恒刀阵',tag:'顶点天赋',description:'永久维持旋风斩',talent:'eternal',requires:'cooldown'}];
  if(this.classId==='frost-mage')return[...common,{id:'frost-damage',title:'碎冰',tag:'冰霜',description:'寒冰箭伤害 +25%',talent:'damage',repeat:true},{id:'deep-freeze',title:'深度冻结',tag:'冰霜',description:'寒冰箭减速效果增强',talent:'control',repeat:true},{id:'ice-lance',title:'冰枪齐射',tag:'冰霜',description:'额外发射一枚寒冰箭',talent:'multishot'},{id:'winter',title:'凛冬将至',tag:'顶点天赋',description:'施法频率大幅提升',talent:'speed',requires:'ice-lance'}];
  if(this.classId==='fire-mage')return[...common,{id:'fire-damage',title:'烈焰增幅',tag:'火焰',description:'火球伤害 +25%',talent:'damage',repeat:true},{id:'quick-fire',title:'火焰冲击',tag:'火焰',description:'火球施放速度 +18%',talent:'speed',repeat:true},{id:'split-fire',title:'凤凰火焰',tag:'火焰',description:'额外发射一枚火球',talent:'multishot'},{id:'pyro',title:'炎爆术',tag:'顶点天赋',description:'火球再次获得 25% 伤害',talent:'damage',requires:'split-fire'}];
  return[...common,{id:'bite',title:'凶猛撕咬',tag:'兽王',description:'杀戮命令伤害 +25%',talent:'damage',repeat:true},{id:'frenzy',title:'狂野怒火',tag:'兽王',description:'命令频率 +18%',talent:'speed',repeat:true},{id:'pack',title:'兽群领袖',tag:'兽王',description:'额外召来一只灵兽',talent:'multishot'},{id:'stampede',title:'万兽奔腾',tag:'顶点天赋',description:'再召来一只灵兽',talent:'multishot',requires:'pack'}];}
}
