import Phaser from 'phaser'; import { Player } from '../entities/Player'; import { Weapon,type SkillTalent } from '../combat/Weapon'; import { GameUI } from '../ui/UI'; import type { ClassId } from '../classes'; import { getUpgradeRewardType } from './upgradeRules';
export type Upgrade={id:string;title:string;tag:string;description:string;apply:()=>void};
export type Talent=Omit<Upgrade,'apply'>&{talent?:SkillTalent;requires?:string;repeat?:boolean;maxRank?:number};
export function getClassTalents(classId:ClassId):Talent[]{
 if(classId==='berserker')return[{id:'rotational-momentum',title:'旋转动力',tag:'双技能联动',description:'旋风斩每命中 1 个目标，使下一次致死打击伤害 +5% / +7% / +9%（当前选择会提升一级）',talent:'rotational-momentum',repeat:true,maxRank:3},{id:'deep-wounds',title:'重伤',tag:'双技能联动',description:'所有技能暴击施加 6 秒重伤；每秒造成攻击强度 ×12% / 18% / 24% ×（1+急速）的伤害（当前选择会提升一级）',talent:'deep-wounds',repeat:true,maxRank:3},{id:'range',title:'扩张利刃',tag:'旋风斩',description:'范围 +20%',talent:'range',repeat:true},{id:'duration',title:'延长风暴',tag:'旋风斩',description:'持续时间 +1 秒',talent:'duration',repeat:true},{id:'fury',title:'沸腾怒火',tag:'狂怒',description:'命中产生双倍怒气',talent:'fury'},{id:'twin',title:'双斧',tag:'狂怒',description:'追加 55% 反向斩击',talent:'twin'},{id:'cooldown',title:'越战越勇',tag:'狂怒',description:'每命中10敌人延长旋转',talent:'cooldown',requires:'fury'},{id:'blood',title:'血路',tag:'狂怒',description:'击杀恢复 1% 生命',talent:'blood'},{id:'eternal',title:'永恒刀阵',tag:'顶点天赋',description:'永久维持旋风斩',talent:'eternal',requires:'cooldown'}];
 if(classId==='frost-mage')return[{id:'frost-damage',title:'碎冰',tag:'冰霜',description:'寒冰箭伤害 +25%',talent:'damage',repeat:true},{id:'deep-freeze',title:'深度冻结',tag:'冰霜',description:'寒冰箭减速效果增强',talent:'control',repeat:true},{id:'frost-speed',title:'刺骨疾风',tag:'冰霜',description:'寒冰箭施放速度 +18%',talent:'speed',repeat:true},{id:'ice-lance',title:'冰枪齐射',tag:'冰霜',description:'额外发射一枚寒冰箭',talent:'multishot',repeat:true},{id:'winter',title:'凛冬将至',tag:'顶点天赋',description:'施法频率大幅提升',talent:'speed',requires:'ice-lance'}];
 if(classId==='fire-mage')return[{id:'combustion',title:'炽燃',tag:'被动释放',description:'火焰暴击叠层；3 层强化并必爆下一次火焰法术，增伤 100% / 150% / 200%',talent:'combustion',repeat:true,maxRank:3},{id:'flame-storm',title:'烈焰风暴',tag:'被动释放',description:'自动召唤持续 5 秒的火焰风暴；升级提高伤害、范围与频率',talent:'flame-storm',repeat:true,maxRank:3},{id:'pyroblast',title:'炎爆术',tag:'被动释放',description:'自动释放高伤炎爆并叠加点燃；升级将点燃延长至 4 / 6 / 8 秒',talent:'pyroblast',repeat:true,maxRank:3},{id:'hot-streak',title:'炽热连击',tag:'顶点天赋',description:'炽燃达到 3 层时立即释放一次炎爆术，并消耗炽燃触发其完整强化',talent:'hot-streak',requires:'combustion'},{id:'fire-damage',title:'烈焰增幅',tag:'火焰',description:'所有火焰法术伤害 +25%',talent:'damage',repeat:true},{id:'quick-fire',title:'火焰冲击',tag:'火焰',description:'火焰法术施放速度 +18%',talent:'speed',repeat:true},{id:'split-fire',title:'凤凰火焰',tag:'火焰',description:'额外发射一枚火球',talent:'multishot',repeat:true}];
 return[{id:'bite',title:'凶猛撕咬',tag:'兽王',description:'杀戮命令伤害 +25%',talent:'damage',repeat:true},{id:'frenzy',title:'狂野怒火',tag:'兽王',description:'命令频率 +18%',talent:'speed',repeat:true},{id:'predator',title:'捕食本能',tag:'兽王',description:'杀戮命令再次获得 25% 伤害',talent:'damage',repeat:true},{id:'pack',title:'兽群领袖',tag:'兽王',description:'额外召来一只灵兽',talent:'multishot',repeat:true},{id:'stampede',title:'万兽奔腾',tag:'顶点天赋',description:'再召来一只灵兽',talent:'multishot',requires:'pack'}];
}
export class LevelSystem{
 private owned=new Map<string,number>();private choosing=false;private queued=0;
 constructor(private scene:Phaser.Scene,private player:Player,private weapon:Weapon,private ui:GameUI,private classId:ClassId){}
 snapshot(){return Object.fromEntries(this.owned);}
 restore(snapshot:Record<string,number>){this.owned=new Map(Object.entries(snapshot));for(const talent of getClassTalents(this.classId)){const count=this.owned.get(talent.id)??0;if(talent.talent)for(let i=0;i<count;i++)this.ui.recordTalent(talent);}}
 show(){if(this.choosing){this.queued++;return;}this.choosing=true;this.scene.physics.pause();const rewardType=getUpgradeRewardType(this.player.level);const available=this.pool(rewardType).filter(t=>(!t.requires||this.owned.has(t.requires))&&(t.repeat||!this.owned.has(t.id))&&(!t.maxRank||(this.owned.get(t.id)??0)<t.maxRank));const items=Phaser.Utils.Array.Shuffle(available).slice(0,4).map(t=>({...t,apply:()=>this.apply(t)}));this.ui.showUpgrades(items,rewardType,u=>{if(!this.choosing)return;this.choosing=false;u.apply();this.ui.hideUpgrades();this.scene.physics.resume();if(this.queued){this.queued--;this.scene.time.delayedCall(0,()=>this.show());}});}
 private apply(t:Talent){this.owned.set(t.id,(this.owned.get(t.id)??0)+1);if(t.talent){this.weapon.applyTalent(t.talent);this.ui.recordTalent(t);}if(t.id==='power'){this.player.attackPower*=1.18;this.player.spellPower*=1.18;}if(t.id==='stride')this.player.speed*=1.12;if(t.id==='vitality'){this.player.maxHp+=20;this.player.heal(20);}if(t.id==='armor')this.player.armor+=12;if(t.id==='resistance')this.player.magicResistance+=12;if(t.id==='haste')this.player.haste+=8;if(t.id==='versatility')this.player.versatility+=8;if(t.id==='mastery')this.player.mastery+=5;}
 private pool(rewardType:'skill'|'attribute'):Talent[]{
  const attributes:Talent[]=[{id:'power',title:'力量与智力',tag:'基础属性',description:'攻击强度与法术强度 +18%',repeat:true},{id:'stride',title:'迅捷步法',tag:'基础属性',description:'速度 +12%',repeat:true},{id:'vitality',title:'坚韧体魄',tag:'基础属性',description:'最大生命 +20，并立即回复',repeat:true},{id:'armor',title:'厚重护甲',tag:'基础属性',description:'护甲 +12',repeat:true},{id:'resistance',title:'符文屏障',tag:'基础属性',description:'魔抗 +12',repeat:true},{id:'haste',title:'急速训练',tag:'基础属性',description:'急速 +8%',repeat:true},{id:'versatility',title:'全能磨炼',tag:'基础属性',description:'全能伤害率 +8%',repeat:true},{id:'mastery',title:'精通研习',tag:'基础属性',description:'精通 +5',repeat:true}];
  if(rewardType==='attribute')return attributes;
  return getClassTalents(this.classId);}
}
