import Phaser from 'phaser';
import { Player } from '../entities/Player'; import { Enemy } from '../entities/Enemy'; import { Weapon } from '../combat/Weapon';
import { Spawner } from '../systems/Spawner'; import { LevelSystem } from '../systems/LevelSystem'; import { ShopSystem } from '../systems/ShopSystem'; import { GameUI,showClassSelection } from '../ui/UI'; import type { ClassId } from '../classes';
export class GameScene extends Phaser.Scene{
 private player?:Player;private enemies?:Phaser.Physics.Arcade.Group;private enemyProjectiles?:Phaser.Physics.Arcade.Group;private weapon?:Weapon;private spawner?:Spawner;private ui?:GameUI;private shop?:ShopSystem;private started=0;private ended=false;private lightningWarnings=new Set<Phaser.GameObjects.Graphics>();private bossWarnings=new Set<Phaser.GameObjects.Graphics>();private bossTimers=new Set<Phaser.Time.TimerEvent>();private classId?:ClassId;
 constructor(){super('game');}
 create(){this.makeTextures();this.physics.world.setBounds(0,0,3200,3200);this.drawWorld();this.cameras.main.centerOn(1600,1600);showClassSelection(this,id=>this.startRun(id));}
 update(time:number){if(this.ended||!this.player||!this.enemies||!this.weapon||!this.spawner||!this.ui)return;this.player.update(time);this.enemies.getChildren().forEach(e=>(e as Enemy).updateBehavior(this.player!,time));this.weapon.update(time);const elapsed=(time-this.started)/1000;this.spawner.update(elapsed);this.ui.update(elapsed);}
 private startRun(classId:ClassId){
  this.classId=classId;
  this.player=new Player(this,1600,1600);this.enemies=this.physics.add.group({runChildUpdate:false});this.enemyProjectiles=this.physics.add.group({runChildUpdate:false});this.weapon=new Weapon(this,this.player,this.enemies,classId);this.ui=new GameUI(this,this.player,classId);const levels=new LevelSystem(this,this.player,this.weapon,this.ui,classId);this.spawner=new Spawner(this,this.enemies,this.player);this.shop=new ShopSystem(this.player,this.weapon);this.spawner.start();
  this.events.on('skill-hit',(enemy:Enemy)=>{if(enemy.hp<=0&&enemy.active){const x=enemy.x,y=enemy.y;enemy.destroy();this.createDrop(x,y,()=>{this.player!.gainAzerite(Phaser.Math.Between(3,6));if(this.player!.gainXp(12))levels.show();});}});
  this.events.on('shaman-lightning',(x:number,y:number)=>this.createLightningStrike(x,y,classId));
  this.events.on('ogre-fire-fists',(x:number,y:number,targetX:number,targetY:number)=>this.createFireFists(x,y,targetX,targetY,classId));
  this.events.on('whelp-fireburst',(x:number,y:number)=>this.createWhelpFireburst(x,y));
  this.events.on('onyxia-start',()=>this.startOnyxiaEncounter());
  this.events.on('wave-break',(wave:number,resume:()=>void)=>{this.clearEnemyHazards();this.physics.pause();this.ui!.showShop(this.shop!.roll(wave),wave,item=>{if(!this.player!.spendAzerite(item.cost))return false;item.apply();this.ui!.update((this.time.now-this.started)/1000);return true;},()=>{this.physics.resume();resume();});});
  this.physics.add.overlap(this.player,this.enemies,(_p,e)=>{const enemy=e as Enemy;if(enemy.getData('hit'))return;enemy.setData('hit',true);this.player!.hp-=this.player!.reduceAttackDamage(enemy.damage);if(classId==='berserker')this.player!.gainRage(enemy.damage);this.cameras.main.shake(100,.006);this.time.delayedCall(700,()=>enemy.active&&enemy.setData('hit',false));this.checkPlayerDefeated();});
  this.cameras.main.startFollow(this.player,true,.09,.09);this.cameras.main.setZoom(1.05);this.started=this.time.now;
 }
 private startOnyxiaEncounter(){
  this.ui?.showBossBanner('第八波 · Boss', '奥妮克希亚', '雏龙、深呼吸、低吼与灼烧');
  this.addBossTimer(1800,()=>this.summonWhelps(),true,9000);
  this.addBossTimer(3000,()=>this.castOnyxiaFireball(),true,4000);
  this.addBossTimer(6000,()=>this.castGrowl(),true,18000);
  this.addBossTimer(8000,()=>this.castDeepBreath(),true,18000);
  this.addBossTimer(14000,()=>this.castScorch(),true,25000);
 }
 private addBossTimer(delay:number,callback:()=>void,loop=false,repeatDelay=delay){
  const timer=this.time.addEvent({delay,callback,loop,repeat:loop?-1:0,startAt:loop?Math.max(0,delay-repeatDelay):0});
  if(loop&&repeatDelay!==delay){timer.remove();const first=this.time.delayedCall(delay,()=>{callback();if(!this.ended){const repeating=this.time.addEvent({delay:repeatDelay,loop:true,callback});this.bossTimers.add(repeating);}this.bossTimers.delete(first);});this.bossTimers.add(first);return;}
  this.bossTimers.add(timer);
 }
 private getOnyxia(){return this.enemies?.getChildren().find(enemy=>(enemy as Enemy).kind==='onyxia'&&enemy.active) as Enemy|undefined;}
 private summonWhelps(){if(!this.getOnyxia()||!this.spawner)return;for(let i=0;i<4;i++)this.spawner.spawn('onyxiaWhelp',Phaser.Math.Between(180,300));this.ui?.showBossMessage('召唤雏龙', '散开躲避范围火球！');}
 private castOnyxiaFireball(){const boss=this.getOnyxia();if(!boss||!this.player)return;this.fireEnemyProjectile(boss.x,boss.y,this.player.x,this.player.y,260,32,0xff7b38);}
 private createWhelpFireburst(x:number,y:number){for(let i=0;i<8;i++){const angle=i*Math.PI/4;this.fireEnemyProjectile(x,y,x+Math.cos(angle)*100,y+Math.sin(angle)*100,190,16,0xffb05a);}}
 private fireEnemyProjectile(x:number,y:number,targetX:number,targetY:number,speed:number,damage:number,tint:number){
  if(!this.enemyProjectiles||!this.player)return;const angle=Phaser.Math.Angle.Between(x,y,targetX,targetY);const fireball=this.enemyProjectiles.create(x,y,'dragon-fireball') as Phaser.Physics.Arcade.Sprite;fireball.setDepth(6).setTint(tint).setVelocity(Math.cos(angle)*speed,Math.sin(angle)*speed);this.time.delayedCall(4200,()=>fireball.active&&fireball.destroy());this.physics.add.overlap(this.player,fireball,()=>{if(!fireball.active)return;fireball.destroy();this.damagePlayer(damage);});
 }
 private castGrowl(){if(!this.getOnyxia()||!this.player)return;this.player.reverseControls(10000);this.ui?.showBossMessage('低吼', '方向颠倒 10 秒！');this.cameras.main.flash(220,135,55,55,false);}
 private castDeepBreath(){
  if(!this.getOnyxia()||!this.player)return;const view=this.cameras.main.worldView;const safeQuarter=Phaser.Math.Between(0,3),quarterWidth=view.width/4;const warning=this.add.graphics().setDepth(4);for(let quarter=0;quarter<4;quarter++){if(quarter===safeQuarter)continue;warning.fillStyle(0xff6b6b,.25).fillRect(view.x+quarter*quarterWidth,view.y,quarterWidth,view.height);}warning.lineStyle(3,0xff9999,.75).strokeRect(view.x+safeQuarter*quarterWidth,view.y,quarterWidth,view.height);this.bossWarnings.add(warning);this.ui?.showBossMessage('深呼吸', '淡红区域危险，仅 1/4 区域安全！');this.tweens.add({targets:warning,alpha:.45,duration:250,yoyo:true,repeat:5});this.addBossTimer(1800,()=>{if(!this.bossWarnings.delete(warning))return;warning.destroy();const safeLeft=view.x+safeQuarter*quarterWidth;if(this.player&&!(this.player.x>=safeLeft&&this.player.x<=safeLeft+quarterWidth))this.damagePlayer(90);});
 }
 private castScorch(){if(!this.getOnyxia()||!this.player)return;this.ui?.showBossMessage('灼烧', '必定命中：持续失去生命');let ticks=0;const dot=this.time.addEvent({delay:1000,repeat:4,callback:()=>{if(!this.player||this.ended)return;this.damagePlayer(3);if(++ticks===5)this.bossTimers.delete(dot);}});this.bossTimers.add(dot);}
 private damagePlayer(rawDamage:number){if(!this.player||this.ended)return;const damage=this.player.reduceSpellDamage(rawDamage);this.player.hp-=damage;if(this.classId==='berserker')this.player.gainRage(damage);this.cameras.main.shake(150,.01);this.checkPlayerDefeated();}
 private drawWorld(){this.add.rectangle(1600,1600,3200,3200,0x0b1519);const g=this.add.graphics();for(let i=0;i<260;i++){const x=Phaser.Math.Between(0,3200),y=Phaser.Math.Between(0,3200);g.fillStyle(i%7?0x13252a:0x31524a,Phaser.Math.FloatBetween(.25,.7)).fillCircle(x,y,Phaser.Math.Between(2,10));}for(let x=0;x<3200;x+=160)g.lineStyle(1,0x234047,.18).lineBetween(x,0,x,3200);for(let y=0;y<3200;y+=160)g.lineStyle(1,0x234047,.18).lineBetween(0,y,3200,y);}
 private createDrop(x:number,y:number,collect:()=>void){const orb=this.physics.add.sprite(x,y,'xp');let collected=false;const pickup=()=>{if(collected||!orb.active)return;collected=true;orb.destroy();collect();};this.physics.add.overlap(this.player!,orb,pickup);const check=this.time.addEvent({delay:80,loop:true,callback:()=>{if(!orb.active){check.remove();return;}const radius=24+this.player!.pickupRange;if(Phaser.Math.Distance.Between(this.player!.x,this.player!.y,orb.x,orb.y)<=radius){check.remove();pickup();}}});}
 private createLightningStrike(x:number,y:number,classId:ClassId){
  const radius=72,warning=this.add.graphics().setDepth(2);warning.fillStyle(0x55bfff,.18).fillCircle(x,y,radius).lineStyle(3,0x8ee9ff,.9).strokeCircle(x,y,radius);this.lightningWarnings.add(warning);
  this.tweens.add({targets:warning,alpha:.35,duration:180,yoyo:true,repeat:4});
  this.time.delayedCall(1000,()=>{if(!this.lightningWarnings.delete(warning))return;warning.destroy();const blast=this.add.graphics().setDepth(6);blast.fillStyle(0xdffcff,.9).fillCircle(x,y,radius).lineStyle(8,0x65cfff,.8).lineBetween(x,y-110,x,y+15);this.tweens.add({targets:blast,alpha:0,duration:220,onComplete:()=>blast.destroy()});if(!this.player||this.ended||Phaser.Math.Distance.Between(this.player.x,this.player.y,x,y)>radius)return;const damage=this.player.reduceSpellDamage(35);this.player.hp-=damage;if(classId==='berserker')this.player.gainRage(damage);this.cameras.main.shake(180,.012);this.checkPlayerDefeated();});
 }
 private createFireFists(x:number,y:number,targetX:number,targetY:number,classId:ClassId){
  if(!this.enemyProjectiles||!this.player)return;
  const baseAngle=Phaser.Math.Angle.Between(x,y,targetX,targetY);
  [-0.22,0,0.22].forEach(offset=>{
   const fist=this.enemyProjectiles!.create(x,y,'fire-fist') as Phaser.Physics.Arcade.Sprite;
   fist.setDepth(5).setRotation(baseAngle+offset);fist.body!.setCircle(11);fist.setVelocity(Math.cos(baseAngle+offset)*235,Math.sin(baseAngle+offset)*235);
   this.time.delayedCall(4500,()=>fist.active&&fist.destroy());
   this.physics.add.overlap(this.player!,fist,()=>{if(!fist.active||!this.player||this.ended)return;fist.destroy();const damage=this.player.reduceSpellDamage(30);this.player.hp-=damage;if(classId==='berserker')this.player.gainRage(damage);this.cameras.main.shake(160,.01);this.checkPlayerDefeated();});
  });
 }
 private clearLightningWarnings(){this.lightningWarnings.forEach(warning=>warning.destroy());this.lightningWarnings.clear();}
 private clearEnemyHazards(){this.clearLightningWarnings();this.bossWarnings.forEach(warning=>warning.destroy());this.bossWarnings.clear();this.bossTimers.forEach(timer=>timer.remove());this.bossTimers.clear();this.enemyProjectiles?.clear(true,true);}
 private checkPlayerDefeated(){if(!this.player||this.player.hp>0||this.ended)return;this.ended=true;this.clearEnemyHazards();this.physics.pause();this.ui!.gameOver(()=>this.scene.restart());}
 private makeTextures(){const make=(key:string,w:number,h:number,draw:(g:Phaser.GameObjects.Graphics)=>void)=>{const g=this.add.graphics();draw(g);g.generateTexture(key,w,h);g.destroy();};make('player',56,56,g=>{g.fillStyle(0x10221d).fillCircle(28,28,25);g.lineStyle(4,0xd6a84f).strokeCircle(28,28,23);g.fillStyle(0xd33b2f).fillTriangle(28,7,15,41,41,41);g.fillStyle(0xffd35a).fillCircle(28,26,7);});make('wolf',48,40,g=>{g.fillStyle(0x607080).fillTriangle(5,18,13,2,18,18).fillTriangle(30,18,38,2,44,20).fillEllipse(24,24,38,27);g.fillStyle(0xe4493e).fillCircle(17,21,3).fillCircle(31,21,3);});make('swift-claw',48,48,g=>{g.fillStyle(0x1d1026).fillCircle(24,24,20);g.lineStyle(7,0xffa235,1).lineBetween(14,10,5,38).lineBetween(25,7,21,41).lineBetween(36,10,42,38);g.lineStyle(3,0xfff06a,.9).lineBetween(14,10,5,38).lineBetween(25,7,21,41).lineBetween(36,10,42,38);g.fillStyle(0xe02f2f).fillTriangle(32,4,45,17,38,19);});make('murloc-shaman',52,52,g=>{g.fillStyle(0x204b43).fillEllipse(26,29,38,34);g.fillStyle(0x55b99a).fillTriangle(8,27,1,18,13,20).fillTriangle(44,27,51,18,39,20);g.fillStyle(0xffef70).fillCircle(19,25,4).fillCircle(33,25,4);g.lineStyle(4,0x8c6239).lineBetween(42,44,45,5);g.fillStyle(0x65d8ff).fillCircle(45,8,6);});make('fire-fist-ogre',68,68,g=>{g.fillStyle(0x542319).fillCircle(34,36,29);g.fillStyle(0xb85a2c).fillCircle(34,31,22);g.fillStyle(0xffd15c).fillCircle(26,28,4).fillCircle(42,28,4);g.fillStyle(0xff6b24).fillCircle(10,47,10).fillCircle(58,47,10);g.lineStyle(3,0xffd35a).strokeCircle(10,47,8).strokeCircle(58,47,8);});make('fire-fist',30,24,g=>{g.fillStyle(0xff6428,.45).fillEllipse(10,12,20,20);g.fillStyle(0xffb32c).fillRoundedRect(8,4,20,16,6);g.fillStyle(0xffed79).fillCircle(23,9,3).fillCircle(24,15,3);});make('onyxia',112,104,g=>{g.fillStyle(0x1c101f).fillEllipse(56,56,82,68);g.fillStyle(0x532240).fillTriangle(18,55,0,12,45,38).fillTriangle(94,55,112,12,67,38);g.lineStyle(5,0xc05042).strokeEllipse(56,56,78,64);g.fillStyle(0xffb34b).fillCircle(44,51,6).fillCircle(68,51,6);g.fillStyle(0xd94731).fillTriangle(56,63,45,82,67,82);});make('onyxia-whelp',42,38,g=>{g.fillStyle(0x51243b).fillEllipse(21,22,30,24);g.fillTriangle(8,21,0,5,17,15).fillTriangle(34,21,42,5,25,15);g.fillStyle(0xffb34b).fillCircle(17,20,3).fillCircle(26,20,3);});make('dragon-fireball',30,30,g=>{g.fillStyle(0xff5438,.35).fillCircle(15,15,15);g.fillStyle(0xff9b42).fillCircle(15,15,10);g.fillStyle(0xffe09a).fillCircle(15,15,4);});make('flame',28,28,g=>{g.fillStyle(0xff6b24).fillCircle(14,14,12);g.fillStyle(0xffd35a).fillCircle(14,14,6);});make('frost',28,28,g=>{g.fillStyle(0x76d7ff,.35).fillCircle(14,14,13);g.fillStyle(0xd9f6ff).fillTriangle(14,1,7,20,21,20);});make('beast',34,28,g=>{g.fillStyle(0x70c85d,.35).fillCircle(17,14,13);g.fillStyle(0xb8ef8e).fillTriangle(3,22,17,3,31,22);});make('xp',20,20,g=>{g.fillStyle(0x2de2e6,.3).fillCircle(10,10,10);g.fillStyle(0x62f4ff).fillCircle(10,10,5);});}
}
