import Phaser from 'phaser'; import { Player } from '../entities/Player'; import { Enemy } from '../entities/Enemy'; import { Projectile } from '../combat/Projectile'; import { Weapon } from '../combat/Weapon'; import { Spawner } from '../systems/Spawner'; import { LevelSystem } from '../systems/LevelSystem'; import { GameUI } from '../ui/UI';
export class GameScene extends Phaser.Scene {
 private player!:Player;private enemies!:Phaser.Physics.Arcade.Group;private projectiles!:Phaser.Physics.Arcade.Group;private weapon!:Weapon;private spawner!:Spawner;private ui!:GameUI;private started=0;private ended=false;
 constructor(){super('game');}
 create(){this.makeTextures();this.physics.world.setBounds(0,0,3200,3200);this.drawWorld();this.player=new Player(this,1600,1600);this.enemies=this.physics.add.group({runChildUpdate:false});this.projectiles=this.physics.add.group();this.weapon=new Weapon(this,this.player,this.enemies,this.projectiles);this.ui=new GameUI(this,this.player);const levels=new LevelSystem(this,this.player,this.weapon,this.ui);this.spawner=new Spawner(this,this.enemies,this.player);this.spawner.start();this.physics.add.overlap(this.projectiles,this.enemies,(p,e)=>{const shot=p as Projectile,enemy=e as Enemy;enemy.hp-=shot.damage;shot.destroy();this.cameras.main.flash(45,255,120,40);if(enemy.hp<=0){const x=enemy.x,y=enemy.y;enemy.destroy();const orb=this.physics.add.sprite(x,y,'xp');this.physics.add.overlap(this.player,orb,()=>{orb.destroy();if(this.player.gainXp(12))levels.show();});}});this.physics.add.overlap(this.player,this.enemies,(_p,e)=>{const enemy=e as Enemy;if(enemy.getData('hit'))return;enemy.setData('hit',true);this.player.hp-=enemy.damage;this.cameras.main.shake(100,.006);this.time.delayedCall(700,()=>enemy.setData('hit',false));if(this.player.hp<=0&&!this.ended){this.ended=true;this.physics.pause();this.ui.gameOver(()=>this.scene.restart());}});this.cameras.main.startFollow(this.player,true,.09,.09);this.cameras.main.setZoom(1.05);this.started=this.time.now;}
 update(time:number){if(this.ended)return;this.player.update();this.enemies.getChildren().forEach(e=>(e as Enemy).chase(this.player));this.weapon.update(time);const elapsed=(time-this.started)/1000;this.spawner.update(elapsed);this.ui.update(elapsed);}
 private drawWorld(){this.add.rectangle(1600,1600,3200,3200,0x0b1519);const g=this.add.graphics();for(let i=0;i<260;i++){const x=Phaser.Math.Between(0,3200),y=Phaser.Math.Between(0,3200);g.fillStyle(i%7?0x13252a:0x31524a,Phaser.Math.FloatBetween(.25,.7)).fillCircle(x,y,Phaser.Math.Between(2,10));}for(let x=0;x<3200;x+=160)g.lineStyle(1,0x234047,.18).lineBetween(x,0,x,3200);for(let y=0;y<3200;y+=160)g.lineStyle(1,0x234047,.18).lineBetween(0,y,3200,y);}
 private makeTextures(){const make=(key:string,w:number,h:number,draw:(g:Phaser.GameObjects.Graphics)=>void)=>{const g=this.add.graphics();draw(g);g.generateTexture(key,w,h);g.destroy();};make('player',56,56,g=>{g.fillStyle(0x10221d).fillCircle(28,28,25);g.lineStyle(4,0x48c58b).strokeCircle(28,28,23);g.fillStyle(0xe8c26a).fillTriangle(28,8,17,39,39,39);g.fillStyle(0x42e39b).fillCircle(28,26,7);});make('wolf',48,40,g=>{g.fillStyle(0x607080).fillTriangle(5,18,13,2,18,18).fillTriangle(30,18,38,2,44,20).fillEllipse(24,24,38,27);g.fillStyle(0xe4493e).fillCircle(17,21,3).fillCircle(31,21,3);});make('boss',100,100,g=>{g.fillStyle(0x511b18).fillCircle(50,52,44);g.lineStyle(5,0xff6a2a).strokeCircle(50,52,40);g.fillStyle(0xff9b32).fillTriangle(11,34,25,1,37,29).fillTriangle(63,29,77,1,91,34);g.fillStyle(0xffd35a).fillCircle(37,48,6).fillCircle(64,48,6);});make('flame',28,28,g=>{g.fillStyle(0xff6b24).fillCircle(14,14,12);g.fillStyle(0xffd35a).fillCircle(14,14,6);});make('xp',20,20,g=>{g.fillStyle(0x2de2e6,.3).fillCircle(10,10,10);g.fillStyle(0x62f4ff).fillCircle(10,10,5);});}
}
